Add label to parametric pulse schema
Qiskit/ibm-quantum-schemas pull request #4
Opened 2020-11-10 02:03 UTC by nkanazawa1989

This PR adds `label` to parametric pulse schema.

See discussion in [Qiskit/qiskit-terra/#5365](https://github.com/Qiskit/qiskit-terra/pull/5365).

2020-11-10 12:27 UTC, taalexander requested changes
Please bump the minor version number for the schema.

2020-11-10 12:27 UTC, taalexander commented on schemas/examples/qasm_w_pulse_gates.json
> +              "label": "pulse1",
Please leave one parametric pulse without a label to ensure it passes.

2020-11-13 03:56 UTC, nkanazawa1989 commented
Thanks, I added two pulses with and without label for each example. Also updated minor version (is it minor or revision?)

2020-11-13 12:22 UTC, taalexander approved these changes
Looks good to me, @mtreinish?

2020-11-18 17:59 UTC, mtreinish approved these changes
LGTM

2020-11-18 18:00 UTC, merged